// GENERATED by demo/scripts/build.py — do not edit by hand.
// Re-run demo/scripts/build-fixtures.sh after changing questions.py,
// warehouse.py or DEMO_TODAY. See demo/README.md.
import type { CapabilityEntry, ParameterCatalog } from '../../../src/api/types'

/** The backend's own vocabularies, dumped from its code. */
export const CATALOG: {
  capabilities: CapabilityEntry[]
  privileges: Record<string, Record<string, string>>
  labels: Record<string, Record<string, string>>
  levels: Record<string, string[]>
  parameters: ParameterCatalog[]
} = {
  "capabilities": [
    {
      "name": "user.read",
      "group": "People",
      "label": "See the list of people and their accounts."
    },
    {
      "name": "user.manage",
      "group": "People",
      "label": "Invite, edit, disable and remove people."
    },
    {
      "name": "service_user.manage",
      "group": "People",
      "label": "Create service accounts and their API keys."
    },
    {
      "name": "team.read",
      "group": "People",
      "label": "See teams and who is in them."
    },
    {
      "name": "team.manage",
      "group": "People",
      "label": "Create teams and change their membership."
    },
    {
      "name": "role.read",
      "group": "People",
      "label": "See roles and what each one carries."
    },
    {
      "name": "role.manage",
      "group": "People",
      "label": "Create roles and assign them to people."
    },
    {
      "name": "audit.read",
      "group": "Oversight",
      "label": "Read the audit log."
    },
    {
      "name": "access.review",
      "group": "Oversight",
      "label": "Ask who can reach a resource, and why."
    },
    {
      "name": "usage.read",
      "group": "Oversight",
      "label": "Read how many tokens everybody's questions used."
    },
    {
      "name": "connection.create",
      "group": "Creation",
      "label": "Add database connections."
    },
    {
      "name": "llm_config.create",
      "group": "Creation",
      "label": "Add model providers."
    },
    {
      "name": "dashboard.create",
      "group": "Creation",
      "label": "Create dashboards."
    },
    {
      "name": "report.create",
      "group": "Creation",
      "label": "Create reports."
    },
    {
      "name": "conversation.create",
      "group": "Creation",
      "label": "Use Chat."
    },
    {
      "name": "deep.run",
      "group": "Creation",
      "label": "Start a deep analysis — minutes long, and many times a chat answer's cost."
    },
    {
      "name": "settings.manage",
      "group": "System",
      "label": "Change installation settings."
    },
    {
      "name": "benchmark.manage",
      "group": "System",
      "label": "Create and run benchmark sets."
    },
    {
      "name": "eval.run",
      "group": "System",
      "label": "Run the evaluation harness."
    },
    {
      "name": "system.maintenance",
      "group": "System",
      "label": "Run maintenance jobs and sweeps."
    }
  ],
  "privileges": {
    "connection": {
      "describe": "See that it exists — name, engine and disclosure policy, but not its schema.",
      "select": "Ask questions through it and read its schema.",
      "modify": "Edit its host and credentials, re-sync the schema, divide it into sections, test it.",
      "delete": "Delete the connection.",
      "manage": "Grant and revoke access, change the disclosure policy, transfer ownership."
    },
    "knowledge": {
      "describe": "See that the store exists, with template and review counts.",
      "select": "Read templates, reviews, suggestions and benchmark results.",
      "modify": "Create, edit and archive templates; resolve reviews; run a sweep.",
      "delete": "Delete a benchmark set.",
      "manage": "Change embedding settings; grant and revoke curation."
    },
    "semantic_layer": {
      "describe": "See that a layer exists and when it was last written.",
      "select": "Read the published layer, its draft, and its history.",
      "modify": "Edit the draft, publish it, restore a version, import, check an expression, queue a generation.",
      "delete": "Delete the layer.",
      "manage": "Grant and revoke access to it."
    },
    "llm_config": {
      "describe": "See that it exists — provider, model and capabilities. Never the key.",
      "select": "Use it to answer: pick it in Chat, on a tile, or in a report.",
      "modify": "Edit the provider, model or endpoint. Equivalent to disclosing the API key — see the warning in this module.",
      "delete": "Delete it.",
      "manage": "Grant and revoke use of it; transfer ownership."
    },
    "dashboard": {
      "describe": "See that it exists — name, description and tile count.",
      "select": "View it and its results. Each tile still needs access to its own connection.",
      "modify": "Edit it; add, remove and re-lay-out tiles; import.",
      "delete": "Delete the dashboard.",
      "manage": "Grant and revoke access; transfer ownership."
    },
    "report": {
      "describe": "See that it exists — name, description and language.",
      "select": "View it and its runs' results. Still needs access to its connection.",
      "modify": "Edit the outline, sections, blocks and SQL; trigger a run.",
      "delete": "Delete the report or one of its runs.",
      "manage": "Grant and revoke access; transfer ownership."
    },
    "conversation": {
      "describe": "See that it exists — title, connection and when.",
      "select": "Read the transcript and its artifacts.",
      "modify": "Rename it, continue the thread, give feedback.",
      "delete": "Delete the thread.",
      "manage": "Grant and revoke access; transfer ownership."
    },
    "team": {
      "describe": "See that it exists — name and member count.",
      "select": "List its members.",
      "modify": "Add and remove members.",
      "delete": "Delete the team.",
      "manage": "Assign roles to it, grant to it, rename it."
    }
  },
  "labels": {
    "connection": {
      "describe": "Can see it exists",
      "select": "Can query",
      "modify": "Can edit",
      "delete": "Can edit and delete",
      "manage": "Full access"
    },
    "knowledge": {
      "describe": "Can see it exists",
      "select": "Can view",
      "modify": "Can curate",
      "delete": "Can curate and delete",
      "manage": "Full access"
    },
    "semantic_layer": {
      "describe": "Can see it exists",
      "select": "Can view",
      "modify": "Can edit",
      "delete": "Can edit and delete",
      "manage": "Full access"
    },
    "llm_config": {
      "describe": "Can see it exists",
      "select": "Can use",
      "modify": "Can edit",
      "delete": "Can edit and delete",
      "manage": "Full access"
    },
    "dashboard": {
      "describe": "Can see it exists",
      "select": "Can view",
      "modify": "Can edit",
      "delete": "Can edit and delete",
      "manage": "Full access"
    },
    "report": {
      "describe": "Can see it exists",
      "select": "Can view",
      "modify": "Can edit",
      "delete": "Can edit and delete",
      "manage": "Full access"
    },
    "conversation": {
      "describe": "Can see it exists",
      "select": "Can read",
      "modify": "Can reply",
      "delete": "Can reply and delete",
      "manage": "Full access"
    },
    "team": {
      "describe": "Can see it exists",
      "select": "Can see members",
      "modify": "Can change members",
      "delete": "Can delete",
      "manage": "Full access"
    }
  },
  "levels": {
    "connection": [
      "select",
      "modify",
      "manage"
    ],
    "knowledge": [
      "select",
      "modify",
      "manage"
    ],
    "semantic_layer": [
      "select",
      "modify",
      "manage"
    ],
    "llm_config": [
      "select"
    ],
    "dashboard": [
      "select",
      "modify",
      "manage"
    ],
    "report": [
      "select",
      "modify",
      "manage"
    ],
    "conversation": [
      "select"
    ],
    "team": [
      "select",
      "modify",
      "manage"
    ]
  },
  "parameters": [
    {
      "provider": "OpenAI-compatible",
      "completion": [
        {
          "name": "top_p",
          "kind": "number",
          "summary": "Nucleus sampling: consider only the tokens making up this much probability mass. OpenAI recommends changing this or temperature, not both.",
          "example": "0.9",
          "minimum": 0.0,
          "maximum": 1.0
        },
        {
          "name": "frequency_penalty",
          "kind": "number",
          "summary": "Penalise tokens by how often they have already appeared. Positive values reduce verbatim repetition.",
          "example": "0.2",
          "minimum": -2.0,
          "maximum": 2.0
        },
        {
          "name": "presence_penalty",
          "kind": "number",
          "summary": "Penalise tokens that have appeared at all. Positive values push the model towards new subjects.",
          "example": "0.2",
          "minimum": -2.0,
          "maximum": 2.0
        },
        {
          "name": "seed",
          "kind": "integer",
          "summary": "Best-effort determinism: the same seed and the same request should return the same completion. Not a guarantee — the provider may change the backend underneath it.",
          "example": "42"
        },
        {
          "name": "stop",
          "kind": "string_list",
          "summary": "Up to four sequences that end the completion. The sequence itself is not returned.",
          "example": "[\"\\n\\n\"]"
        },
        {
          "name": "logit_bias",
          "kind": "object",
          "summary": "Token id → bias, −100 to 100. A bias of −100 bans a token and 100 forces it. Token ids are the tokenizer's, not words.",
          "example": "{\"50256\": -100}"
        },
        {
          "name": "user",
          "kind": "string",
          "summary": "A stable identifier for the end user, which OpenAI uses to detect abuse. Send an opaque id, never an email address.",
          "example": "team-analytics"
        },
        {
          "name": "service_tier",
          "kind": "string",
          "summary": "Which processing tier to bill and queue this request under.",
          "example": "auto",
          "choices": [
            "auto",
            "default",
            "flex",
            "scale",
            "priority"
          ]
        },
        {
          "name": "store",
          "kind": "boolean",
          "summary": "Ask the provider to retain the completion for its own dashboards and evaluations. Off unless your account wants the history.",
          "example": "false"
        },
        {
          "name": "reasoning_effort",
          "kind": "string",
          "summary": "How long a reasoning model may think before answering. Ignored by models that do not reason.",
          "example": "low",
          "choices": [
            "minimal",
            "low",
            "medium",
            "high"
          ]
        },
        {
          "name": "max_completion_tokens",
          "kind": "integer",
          "summary": "The newer ceiling on generated tokens, counting a reasoning model's hidden thinking. Set this as well as Max tokens when you point this configuration at a reasoning model.",
          "example": "4096",
          "minimum": 1,
          "maximum": 1000000
        },
        {
          "name": "prompt_cache_key",
          "kind": "string",
          "summary": "Groups requests that share a prefix so the provider can serve them from its prompt cache.",
          "example": "datamind-sql"
        },
        {
          "name": "safety_identifier",
          "kind": "string",
          "summary": "An opaque, stable id for the end user, used for policy enforcement. The replacement OpenAI recommends over `user`.",
          "example": "u_8f21"
        },
        {
          "name": "extra_body",
          "kind": "object",
          "summary": "Body fields this endpoint defines for itself — vLLM's top_k, OpenRouter's provider routing. Sent verbatim; the OpenAI client's own passthrough. DataMind checks nothing inside it beyond refusing to let it overwrite the request.",
          "example": "{\"top_k\": 40}"
        }
      ],
      "embedding": [
        {
          "name": "dimensions",
          "kind": "integer",
          "summary": "Ask for shorter vectors. Supported by text-embedding-3 and later; the width DataMind pins is measured from the reply, so this changes the pin rather than contradicting it.",
          "example": "512",
          "minimum": 1,
          "maximum": 16384
        },
        {
          "name": "user",
          "kind": "string",
          "summary": "A stable, opaque end-user identifier, as on completions.",
          "example": "team-analytics"
        },
        {
          "name": "extra_body",
          "kind": "object",
          "summary": "Body fields this embedding endpoint defines for itself. Sent verbatim.",
          "example": "{\"truncate\": \"END\"}"
        }
      ],
      "embedding_supported": true
    },
    {
      "provider": "Anthropic",
      "completion": [
        {
          "name": "top_p",
          "kind": "number",
          "summary": "Nucleus sampling. Anthropic recommends adjusting this or temperature, not both.",
          "example": "0.9",
          "minimum": 0.0,
          "maximum": 1.0
        },
        {
          "name": "top_k",
          "kind": "integer",
          "summary": "Sample from only the K most likely tokens. Anthropic describes it as an advanced control to remove long-tail responses.",
          "example": "40",
          "minimum": 0,
          "maximum": 500
        },
        {
          "name": "stop_sequences",
          "kind": "string_list",
          "summary": "Custom sequences that stop generation. The model's stop_reason becomes stop_sequence when one fires.",
          "example": "[\"\\n\\nHuman:\"]"
        },
        {
          "name": "thinking",
          "kind": "object",
          "summary": "Extended thinking. `{\"type\": \"enabled\", \"budget_tokens\": N}` — the budget must be at least 1024 and below Max tokens. DataMind already forwards a model's thinking to the step trail.",
          "example": "{\"type\": \"enabled\", \"budget_tokens\": 2048}",
          "object_keys": [
            "type",
            "budget_tokens"
          ]
        },
        {
          "name": "metadata",
          "kind": "object",
          "summary": "`{\"user_id\": \"…\"}` — an opaque identifier for the end user, used by Anthropic for abuse detection. Never a name, an email or a phone number.",
          "example": "{\"user_id\": \"u_8f21\"}",
          "object_keys": [
            "user_id"
          ]
        }
      ],
      "embedding": [],
      "embedding_supported": false
    }
  ]
}
